### ISSUE TITLE
on Untiy2020.2 reflection is up side down and with many flickering in reflection

### ISSUE THREAD

**Issue by FinalKing** [ColinLeung-NiloCat/UnityURP-MobileScreenSpacePlanarReflection#6]
on Untiy2020.2 reflection is up side down and with many flickering in reflection

![image](https://user-images.githubusercontent.com/7523985/113374523-e4a47b80-939f-11eb-98e5-19589b964010.png)

**Comment by inarutom2014** [comment]
> on Untiy2020.2 reflection is up side down and with many flickering in reflection
> 
> ![image](https://user-images.githubusercontent.com/7523985/113374523-e4a47b80-939f-11eb-98e5-19589b964010.png)


这个问题我也遇到了 是因为通过深度还原世界坐标的地方 平台适配有问题 加上下面的代码就可以了
位置在获取深度后 通过screenuv和depth获得clip sapce的position下面
#if UNITY_UV_STARTS_AT_TOP
		// Our world space, view space, screen space and NDC space are Y-up.
		// Our clip space is flipped upside-down due to poor legacy Unity design.
		// The flip is baked into the projection matrix, so we only have to flip
		// manually when going from CS to NDC and back.
		posCS.y = -posCS.y;
#endif

**Comment by ColinLeung-NiloCat** [comment]
a fix has been merged, you can pull the latest version and retry it in the latest Unity2020.3.x
