### ISSUE TITLE
Horizontral Rection Plane Height WS is not Correct 

### ISSUE THREAD

**Issue by goesByhc** [ColinLeung-NiloCat/UnityURP-MobileScreenSpacePlanarReflection#7]
When I change the SSRPGround's world pos Y to 1, and change the Horizontral Rection Plane Height WS in settings to 1.
The Reflection is not work correctly.
![image](https://user-images.githubusercontent.com/13200593/144576710-3fdd0e59-6a6d-404c-8096-fb67d8814ff6.png)

**Comment by goesByhc** [comment]
If planar world pos is negative, the reflection is working correctly.

**Comment by ColinLeung-NiloCat** [comment]
a fix has been merged, you can pull the latest version and retry it in the latest Unity2020.3.x

**Comment by Torgo13** [comment]
Unfortunately the problem @goesByhc mentioned is still there. I tested it in both 2020.3.39 LTS and 2021.3.11 LTS.

You can set the position to be negative but the reflection gets more faint the further down you move it, so it looks OK at y=-5 but is very faint by y=-10.

Any y value above 0 results in a missing part of the reflection like in the screenshot.
